[package]
name = "go-to"
version = "0.1.0"
authors = ["rudy3091 <grayblack313@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
